### PR TITLE
Replacing favicons.

### PR DESCRIPTION
**Pull request by Ncookiez**
Adding a white background to 3 favicons in order to be more visible in dark-themed browsers.

### CODE REVIEW

**Comment by HaoyuanLi** [comment]
Is it possible to make the background to be transparent? That way it'd work better for different colours I feel like

**Comment by Ncookiez** [comment]
@HaoyuanLi The favicon's backgrounds at the moment are transparent. The reason for the white backgrounds is because the logo (greyish-black) is invisible in any dark-themed browsers. Sorry I didn't make that clear enough on the request.

**Comment by psiemens** [comment]
What if we kept the transparent background and changed the colour from white to red? That way it'd be visible and dark and light backgrounds without the need for a white box.

**Comment by Ncookiez** [comment]
That could work, but from what I've tried editing .ico files can be quite a pain. Unless you know a good program to do so?

**Comment by psiemens** [comment]
You can actually use this tool to convert an SVG to PNG and ICO favicon files: https://www.favicon-generator.org/

I'll send you an SVG version on Slack! You should be able to change the colours pretty easily.

**Comment by Ncookiez** [comment]
I'll keep this open for now, but let's see what it looks like with red favicons :)

**Pull request closed without merging**
